name: condarise

on:
  push:
    branches:
      - main
env:
  atoken: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
  recipe_path: conda/recipe
  env_yaml_path: conda/env
  VERSION: '0.3.2' # versioned by bump2version

jobs:
  condarise:
    # When merging to main and the commit message starts with 'Bump version:'
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Conda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Micromamba setup
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.4.9-0'
          environment-file: ${{ env.env_yaml_path }}/condabuild.yaml
      - name: 🐍 Conda pkg build and upload
        run: |
          conda mambabuild --R 4.2 ${recipe_path} --token ${atoken} -c umccr -c bioconda -c conda-forge
